//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr3_IGORA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Service
    {
        public int ID { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IDService { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Service Service { get; set; }
    }
}
