//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr3_IGORA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Orders_Service = new HashSet<Orders_Service>();
        }
    
        public int IDOrder { get; set; }
        public Nullable<System.DateTime> DateTime_Order { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDStatus { get; set; }
        public Nullable<System.DateTime> Date_CloseOrder { get; set; }
        public Nullable<int> Time_Rent { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Service> Orders_Service { get; set; }
        public virtual Status Status { get; set; }
    }
}
